MusalovKR/Controllers/ExecutionController.cs
using Microsoft.AspNetCore.Mvc;
using MusalovKR.Repositories;

namespace MusalovKR.Controllers
{
    public class ExecutionController : Controller
    {
        private readonly PostsRepository repository;

        public ExecutionController(PostsRepository repository)
        {
            this.repository = repository;
        }

        public IActionResult Index(string query)
        {
            if (query == null) return View();

            try
            {
                var result = repository.ReadWithScript(query);
                return View(result);
            }
            catch (Exception e)
            {
                ViewData.Add("response", e.Message);
                return View();
            }
        }
    }
}

MusalovKR/Controllers/PostsController.cs
using Common;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MusalovKR.Controllers
{
    public class PostsController : Controller
    {
        private readonly AppDbContext _context;

        public PostsController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Posts.ToList());
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var posts = await _context.Posts
                .FirstOrDefaultAsync(m => m.ID_Posts == id);
            if (posts == null)
            {
                return NotFound();
            }

            return View(posts);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID_Posts,Tittle,PayCheck,Responsibility,Requirements")] Posts posts)
        {
            if (ModelState.IsValid)
            {
                _context.Add(posts);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(posts);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var posts = await _context.Posts.FindAsync(id);
            if (posts == null)
            {
                return NotFound();
            }
            return View(posts);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID_Posts,Tittle,PayCheck,Responsibility,Requirements")] Posts posts)
        {
            if (id != posts.ID_Posts)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(posts);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostsExists(posts.ID_Posts))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(posts);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var posts = await _context.Posts
                .FirstOrDefaultAsync(m => m.ID_Posts == id);
            if (posts == null)
            {
                return NotFound();
            }

            return View(posts);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Posts == null)
            {
                return Problem("Entity set 'AppDbContext.Posts'  is null.");
            }
            var posts = await _context.Posts.FindAsync(id);
            if (posts != null)
            {
                _context.Posts.Remove(posts);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostsExists(int id)
        {
            return (_context.Posts?.Any(e => e.ID_Posts == id)).GetValueOrDefault();
        }
    }
}

MusalovKR/Controllers/StoredProcedureController.cs
using Common;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace MusalovKR.Controllers
{
    public class StoredProcedureController : Controller
    {
        private readonly AppDbContext _context;

        public StoredProcedureController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(ExecutionScript model)
        {
            if (string.IsNullOrEmpty(model.Script)) return View(model);

            if (model.InputVariables.Count == 0 | model.OutputVariables.Count == 0)  // парсим названия переменных 
            {
                string[] parts = model.Script.Split(',');
                List<string> variables = new();

                foreach (string part in parts)
                {
                    variables.Add(part[part.IndexOf("@")..part.Length]);
                }

                foreach (var s in variables)
                {
                    if (s.ToLower().Contains("output"))
                        model.OutputVariables.Add(new(s.Split(' ')[0], null!));
                    else
                        model.InputVariables.Add(new(s, null!));
                }

                var newModel = new ExecutionScript
                {
                    Script = model.Script,
                    NeedParse = model.NeedParse,
                    InputVariables = model.InputVariables,
                    OutputVariables = model.OutputVariables
                };

                return View(newModel);
            }
            else
            {
                model.Result = Execution(model);
                return View(model);
            }
        }

        private string Execution(ExecutionScript query)
        {
            var parameters = new List<SqlParameter>();

            for (int i = 0; i < query.InputVariables.Count; i++)
            {
                parameters.Add(new()
                {
                    ParameterName = query.InputVariables[i].Name,
                    Value = query.InputVariables[i].Value,
                    Direction = query.InputVariables[i].Value is null ? ParameterDirection.Output : ParameterDirection.Input,
                    Size = int.MaxValue
                });
            }
            for (int i = 0; i < query.OutputVariables.Count; i++)
            {
                parameters.Add(new()
                {
                    ParameterName = query.OutputVariables[i].Name,
                    Value = query.OutputVariables[i].Value,
                    Direction = query.OutputVariables[i].Value is null ? ParameterDirection.Output : ParameterDirection.Input,
                    Size = int.MaxValue
                });
            }

            _context.Database.ExecuteSqlRaw(query.Script, parameters);
            return parameters.LastOrDefault().Value.ToString();
        }
    }
}

MusalovKR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Musalov.KR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MusalovKR.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Musalov.KR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Список</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Index" asp-controller="Posts">Таблица</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Index" asp-controller="Execution">Запрос</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Index" asp-controller="StoredProcedure">Хранимая процедура</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MusalovKR - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>